const language = {
  English: {
    title: "Todoship",
    menu: {
      todo: "Todo",
      calendar: "WorkFlow",
    },
    warning: "Warning",
    noBefore: "Please do not select a date before today",
    buttons: {
      add: "Add",
      delete: "Delete",
      edit: "Edit",
      confirm: "Confirm",
      cancel: "Cancel",
      login: "Login",
    },
    reallyDelete: "Are you sure to delete this item?",
    todo: {
      title: "TodoList",
      add: "Add",
      itemText: {
        work: "Work",
        life: "Life",
        study: "Study",
        detailHead: "Detail",
        detailTitle: "Title",
        detailDesc: "Content",
        detailDDL: "Deadline",
        detailType: "Type",
        // 还有多久截止
        detailFromEnd: "From End: ",
        detailDay: " day(s)",
        detailDelete: "Delete",
        detailQuit: "Quit",
      },
    },
    workflow: {
      title: "Work Flow",
      addThings: "Add Things",
      addTitle: "Title",
      addContent: "Content",
      addDDL: "Deadline",
      addExample: "Example: xx HomeWork",
      addNewFlow: "Add New Flow",
      addNewFlowTitle: "Title",
      addNewFlowEx: "Example: Computer Graphics",
    },
    setting: {
      title: "Setting",
      ok: "OK",
      cancel: "Close",
      language: "语言",
    },
    week: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
  },
  Chinese: {
    title: "Todoship",
    menu: {
      todo: "待办事项",
      calendar: "工作流",
    },
    buttons: {
      add: "添加",
      delete: "删除",
      edit: "编辑",
      confirm: "确认",
      cancel: "取消",
      login: "登录",
    },
    warning: "警告",
    noBefore: "请不要选择今天之前的日期",
    reallyDelete: "删除操作不可逆，确定要删除这个事项吗？",
    todo: {
      title: "待办列表",
      add: "添加",
      addNewTodo: "添加新待办",
      itemText: {
        work: "工作",
        life: "生活",
        study: "学习",
        detailHead: "详情",
        detailTitle: "标题",
        detailDesc: "内容",
        detailDDL: "截止日期",
        detailType: "类型",
        // 还有多久截止
        detailFromEnd: "距离截止还有：",
        detailDay: " 天",
        detailDelete: "删除",
        detailQuit: "退出",
      },
    },
    workflow: {
      title: "工作流",
      addThings: "添加事项",
      addTitle: "标题",
      addContent: "内容",
      addDDL: "截止日期",
      addExample: "例如：xx作业",
      addNewFlow: "添加新的工作流",
      addNewFlowEx: "如：xx课程",
    },
    setting: {
      title: "设置",
      ok: "确定",
      cancel: "关闭",
      language: "Language",
    },
    week: [
      "星期日",
      "星期一",
      "星期二",
      "星期三",
      "星期四",
      "星期五",
      "星期六",
    ],
  },
};

export default language;
